[rollinghall]
title = "롤링홀"
url = "http://www.rollinghall.co.kr/default/mp3/mp3_sub2.php?sub=02"
entrySelector = "div.col-sm-9 table td.boxArea"
titleSelector = "span.gallery_title"
linkSelector = "tr.nSize td a"
contentSelector = "td.gallery_etc font"
imageSelector = "tr.nSize img"
onFail = "stale"

[gurumare]
title = "구름아래소극장 ─ 공연안내"
url = "http://gurumare.co.kr/show"
entrySelector = "div.col-xs-6.col-lg-3.col-md-6"
titleSelector = "b"
linkSelector = "div a"
imageSelector = "a img"
waitUntil = "networkidle"
onFail = "stale"

[yes24livehall]
title = "예스24 라이브홀"
url = "https://yes24livehall.com/ko/show/list.php"
entrySelector = "div.shows"
titleSelector = "a.title"
linkSelector = "a"
contentSelector = "a.datetime"
imageSelector = "a.poster img"
waitUntil = "networkidle"
onFail = "stale"

[cjazit]
title = "CJ문화재단 ─ 공연예매"
url = "https://www.cjazit.org/cjazit/book/list"
entrySelector = "div.list div.item"
titleSelector = "h3.item-heading"
linkSelector = "div.item-body a"
contentSelector = "div.item-details"
imageSelector = "div.item-thumb img"
waitUntil = "networkidle"
onFail = "stale"

[west-bridge]
title = "웨스트브릿지 ─ 예정공연"
url = "http://www.west-bridge.co.kr/livehall/reserveShow.asp?status=exp"
entrySelector = "ul.liveProduct li"
titleSelector = "dd.pnamEllipsis a"
linkSelector = "dd.pnamEllipsis a"
contentSelector = "dl.liveConcertTime > dd"
imageSelector = "dl:nth-child(1) > dd > a > img"
waitUntil = "networkidle"
onFail = "stale"

[workshall]
title = "폼텍웍스홀 ─ 공연안내 ─ 예정공연"
url = "http://www.workshall.co.kr/play/show_list.html"
entrySelector = "div[class='col-md-3 col-sm-6 wedo padding-0']"
titleSelector = "a.title"
linkSelector = "a.title"
contentSelector = "a.datetime"
imageSelector = "div.gri > figure > a > img"
waitUntil = "networkidle"
onFail = "stale"

[bluesquare]
title = "블루스퀘어 ─ 공연안내"
url = "http://www.bluesquare.kr/Goods/AllPerformanceList.asp?m_menu=performance&s_menu=all"
entrySelector = "div.Pall"
titleSelector = "dl dt.subject"
linkSelector = "div.btn p:nth-child(1) a"
contentSelector = "dl"
imageSelector = "p.poster img"
waitUntil = "networkidle"

[sangsangmadang]
title = "상상마당 ─ 공연정보"
url = "https://www.sangsangmadang.com/show/HD"
entrySelector = "ul.gallery_list.type2.movie_list li"
titleSelector = "div.info h4"
linkSelector = "a.thumb_type2"
contentSelector = "div.detail span:nth-child(2)"
waitUntil = "networkidle"
