[rollinghall]
title = "롤링홀"
url = "http://www.rollinghall.co.kr/default/mp3/mp3_sub2.php?sub=02"
entrySelector = "div.col-sm-9 table td.boxArea"
titleSelector = "span.gallery_title"
linkSelector = "tr.nSize td a"
contentSelector = "td.gallery_etc font"
imageSelector = "tr.nSize img"
onFail = "stale"

[gurumare]
title = "구름아래소극장 ─ 공연안내"
url = "http://gurumare.co.kr/show"
entrySelector = "div.col-xs-6.col-lg-3.col-md-6"
titleSelector = "b"
linkSelector = "div a"
imageSelector = "a img"
waitUntil = "networkidle"
onFail = "stale"

[yes24livehall]
title = "예스24 라이브홀"
url = "https://yes24livehall.com/ko/show/list.php"
entrySelector = "div.shows"
titleSelector = "a.title"
linkSelector = "a"
contentSelector = "a.datetime"
imageSelector = "a.poster img"
waitUntil = "networkidle"
onFail = "stale"

[cjazit]
title = "CJ문화재단 ─ 공연예매"
url = "https://www.cjazit.org/cjazit/book/list"
entrySelector = "div.list div.item"
titleSelector = "h3.item-heading"
linkSelector = "div.item-body a"
contentSelector = "div.item-details"
imageSelector = "div.item-thumb img"
waitUntil = "networkidle"
onFail = "stale"

[west-bridge]
title = "웨스트브릿지 ─ 예정공연"
url = "http://www.west-bridge.co.kr/livehall/reserveShow.asp?status=exp"
entrySelector = "ul.liveProduct li"
titleSelector = "dd.pnamEllipsis a"
linkSelector = "dd.pnamEllipsis a"
contentSelector = "dl.liveConcertTime > dd"
imageSelector = "dl:nth-child(1) > dd > a > img"
waitUntil = "networkidle"
onFail = "stale"

[workshall]
title = "폼텍웍스홀 ─ 공연안내 ─ 예정공연"
url = "http://www.workshall.co.kr/play/show_list.html"
entrySelector = "div[class='col-md-3 col-sm-6 wedo padding-0']"
titleSelector = "a.title"
linkSelector = "a.title"
contentSelector = "a.datetime"
imageSelector = "div.gri > figure > a > img"
waitUntil = "networkidle"
onFail = "stale"

[bluesquare]
title = "블루스퀘어 ─ 공연안내"
url = "http://www.bluesquare.kr/Goods/AllPerformanceList.asp?m_menu=performance&s_menu=all"
entrySelector = "div.Pall"
titleSelector = "dl dt.subject"
linkSelector = "div.btn p:nth-child(1) a"
contentSelector = "dl"
imageSelector = "p.poster img"
waitUntil = "networkidle"

[sangsangmadang]
title = "상상마당 ─ 공연정보"
url = "https://www.sangsangmadang.com/show/HD"
entrySelector = "ul.gallery_list.type2.movie_list li"
titleSelector = "div.info h4"
linkSelector = "a.thumb_type2"
contentSelector = "div.detail span:nth-child(2)"
waitUntil = "networkidle"

[samsunghall]
title = "이화여대 삼성홀 ─ 공연안내"
url = "http://samsunghall.interpark.com/performance/ListAjax.asp"
entrySelector = "body > table > tbody > tr:nth-child(2) > td:nth-child(3) > table > tbody > tr:nth-child(2) > td > table > tbody > tr:nth-child(1),tr:nth-child(5),tr:nth-child(9),tr:nth-child(13),tr:nth-child(17),tr:nth-child(21),tr:nth-child(25),tr:nth-child(29),tr:nth-child(33),tr:nth-child(37),tr:nth-child(41),tr:nth-child(45),tr:nth-child(49),tr:nth-child(53),tr:nth-child(57),tr:nth-child(61)"
titleSelector = "td:nth-child(3) > p"
linkSelector = "a:nth-child(8)"
contentSelector = "td:nth-child(3)"
imageSelector = "td:nth-child(1) > img"
waitUntil = "networkidle"

[nodeulmusic_linktree]
title = "노들섬 라이브하우스 ─ 링크트리"
url = "https://linktr.ee/nodeul.music"
entrySelector = "div.sc-bdfBwQ.pkAuV"
titleSelector = "p[class='sc-hKgILt Button__StyledText-sc-uh5tyw-0 kVCYxL rsIfq']"
linkSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh']"

[ctrsound_linktree]
title = "씨티알사운드 ─ 링크트리"
url = "https://linktr.ee/CTRSOUND"
entrySelector = "div.sc-bdfBwQ.pkAuV"
titleSelector = "p[class='sc-hKgILt Button__StyledText-sc-uh5tyw-0 kVCYxL rsIfq']"
linkSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh']"

[prismhall_linktree]
title = "프리즘홀 ─ 링크트리"
url = "https://linktr.ee/prismhall"
entrySelector = "div.sc-bdfBwQ.pkAuV"
titleSelector = "p[class='sc-hKgILt Button__StyledText-sc-uh5tyw-0 kVCYxL rsIfq']"
linkSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh']"

[cafeunplugged_linktree]
title = "카페 언플러그드 ─ 링크트리"
url = "https://linktr.ee/cafe.unplugged"
entrySelector = "div.sc-bdfBwQ.pkAuV"
titleSelector = "p[class='sc-hKgILt Button__StyledText-sc-uh5tyw-0 kVCYxL rsIfq']"
linkSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh']"

[gongsangondo_linktree]
title = "공상온도 ─ 링크트리"
url = "https://linktr.ee/gongsangondo"
entrySelector = "div.sc-bdfBwQ.pkAuV"
titleSelector = "p[class='sc-hKgILt Button__StyledText-sc-uh5tyw-0 CczVW rsIfq']"
linkSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh']"

[nestnada_inpock]
title = "네스트나다 ─ 인포크링크"
url = "https://link.inpock.co.kr/nestnada"
entrySelector = "//html/body/div/div/div/div/div/div/a/div"
titleSelector = "//div[2]/p[1]"
linkSelector = "//div[2]/p[1]"
imageSelector = "div.image"
waitUntil = "networkidle"
