[rollinghall]
title = "롤링홀"
url = "http://www.rollinghall.co.kr/default/mp3/mp3_sub2.php?sub=02"
entrySelector = "div.col-sm-9 table td.boxArea"
titleSelector = "span.gallery_title"
linkSelector = "tr.nSize td a"
contentSelector = "td.gallery_etc font"
imageSelector = "tr.nSize img"

[gurumare]
title = "구름아래소극장 ─ 공연안내"
url = "http://gurumare.co.kr/show"
entrySelector = "div.col-xs-6.col-lg-3.col-md-6"
titleSelector = "b"
linkSelector = "div a"
imageSelector = "a img"
waitUntil = "networkidle"

[yes24livehall]
title = "예스24 라이브홀"
url = "https://yes24livehall.com/ko/show/list.php"
entrySelector = "div.shows"
titleSelector = "a.title"
linkSelector = "a"
contentSelector = "a.datetime"
imageSelector = "a.poster img"
waitUntil = "networkidle"
